"""Build Tiggy's ten-page local character site using the Python standard library."""
from pathlib import Path
from html import escape
import os

ROOT = Path(__file__).resolve().parents[1]
SIRE_URL = os.environ.get('SIRE_PARTNER_URL', 'https://auraofintelligence.github.io/australiansire/')
VERSION = '20261001-full-character-3'

PAGES = [
    dict(slug='index', title='Tiggy Bestmann', intro='A happy-go-lucky fool with an artist’s imagination, a traveller’s appetite and love in abundance.', image='opening-world', alt='Two adult women, one visibly pregnant, welcome the long-haired Tiggy at an Istanbul ferry landing and draw him into a lively conversation.', caption='Imagined encounter at an Istanbul ferry landing. GenAI artwork.', colour='lemon', body='''
<p class="lead">Tiggy Bestmann wants a life worth getting amongst. Big waves, music festivals, unfamiliar cities, beautiful women and ambitious ideas all catch his interest. He is an artist, a traveller and an occasionally ridiculous romantic, with far more curiosity than concern for looking impressive.</p>
<h2>A conversation changes the day</h2>
<p>At an Istanbul ferry landing, two women strike up a conversation with him. Boats come and go while they talk. One is pregnant; both have places to be and plenty to say. Tiggy’s next few hours become much more interesting than the afternoon he had in mind.</p>
<p>Women begin his first encounters. What follows grows between them: a joke, a shared interest, attraction, an invitation worth accepting. He enjoys women of many forms and personalities, and the <a href="company.html">pleasure of discovering each other</a> is a large part of why he travels.</p>
<h2>The world in all its variety</h2>
<p>Every country and territory is on his wish list. A working visit, an outback gathering, a beach festival and a splendid dinner each offer a different taste of life. He enjoys the change of company as much as the change of scenery.</p>
<p>Time is limited. There are jobs to finish, flights to catch and people he wants to see again. His <a href="out-about.html">travel oracle gathers opportunities</a> as they emerge. An interesting offer gives the journey a new direction; a good reunion gives him a reason to return.</p>
<h2>A past with plenty in it</h2>
<p>Luke Nathan Hayes’s memories run through Tiggy’s developing science-fiction romantasy. Sunshine Coast beach years, Caboolture workshop days, a UK festival season, Darwin airport work and journeys through Asia provide very different starting points.</p>
<p>The fiction moves between those memories and the life Luke wants to explore. <a href="music.html">A Glastonbury crew pass becomes a performance dream.</a> <a href="art.html">An old photograph becomes an entrance into a remembered place.</a> The <a href="fool.html">dog, street and childhood game behind Tiggy’s name</a> give this grown-up adventurer a wonderfully unserious beginning.</p>
<h2>Joyful responsible abundance</h2>
<p>Tiggy’s idea of abundance includes affection, useful work, time to play and company that enjoys being there. He likes contributing to the experience: making the art, helping the event happen, sharing the music and getting into the water.</p>
<p>The horizon reaches far beyond Earth. Festival grounds, <a href="retreats.html">Aura retreats</a> and creative teams lead towards <a href="possibilities.html">lunar playgrounds, solar observatories and encounters with other civilisations</a>. His curiosity travels with him. So does his sense of humour.</p>'''),
    dict(slug='fool', title='The happy-go-lucky fool', intro='Honest first, dignified second. A childhood name, a grown-up joke and an appetite for play.', image='fool-mischief-v2', alt='Long-haired Tiggy laughs with adult friends as a woman playfully tilts his orange hat at an imagined outdoor festival.', caption='Shared mischief at an imagined outdoor festival. GenAI artwork.', colour='orange', body='''
<p class="lead">Tiggy’s honesty occasionally arrives ahead of his dignity. He says what he thinks, enjoys a cheeky joke and finds plenty to laugh about in his own awkward moments. His imagination is ambitious. His sense of himself is much less solemn.</p>
<h2 id="the-name">A dog, a street and a game</h2>
<p>Tiggy was Luke’s childhood dog. Tiggy was also what he called the game of tag. Bestmann Road was his childhood street. The first-pet-plus-first-street porn-star-name game brought the two together: an innocent affection for play, with an adult joke attached.</p>
<p>The boy playing tiggy and the man writing romantasy share an appetite for discovery. Childhood exploration grows into world travel, new company and larger adventures. The name keeps the fun of that beginning.</p>
<h2>The innocent fool</h2>
<p>At a festival, a woman tilts his orange hat and opens the conversation with a joke. Tiggy laughs and answers with one of his own. The art around them is extravagant, the music is getting louder and neither is especially interested in restoring his dignity.</p>
<p>That is his sort of mischief: playful, affectionate and shared. A funny exchange is part of the attraction. He likes the moment they both lose their train of thought because they are laughing, then discover they still want to hear the answer.</p>
<h2>Three faces of the same life</h2>
<p>Tiggy is the open-hearted expression, drawn to joyful, energetic and exploratory companionship with women of many forms and personalities. Australian Sire is the older, more refined and selective expression, exploring fertility and particular deep desires. Luke Nathan Hayes, also known as Luke Catalyst, occupies the middle ground where both meet.</p>
<p><a href="https://auraofintelligence.github.io/australiansire/writer.html#three-personas">Their shared origin</a> gives the fiction three different temperaments. Tiggy’s broad attraction and taste for frivolity remain his own throughout the universe.</p>
<h2>A student of life</h2>
<p>Luke’s early adult years included a Holden Gemini, supermarket shifts, house parties, nightclubs and plenty of time at the beach. He remembers describing his checkout work as “swiping the items and checking out the chicks”. Later came workshop skills, event crews and journeys abroad. The flashbacks move through those changes with the curiosity of someone finding out what he enjoys.</p>
<p>Tiggy brings that curiosity to art, science, philosophy and relationships. Making things with other people gives him new ideas; being attracted to someone gives a conversation another delightful complication. He wants to love and be loved, to enjoy the moment and to have another story worth remembering when it ends.</p>'''),
    dict(slug='company', title='Love, desire and company', intro='A glance across a party, an invitation and the delight of wanting more time together.', image='company-world', alt='Tiggy talks closely with two adult women, one visibly pregnant, at an art-filled rooftop gathering in Mexico City.', caption='Imagined rooftop company in Mexico City. GenAI artwork.', colour='orange', body='''
<p class="lead">Tiggy likes the moment a conversation becomes a flirtation. There is laughter, a little uncertainty and the growing pleasure of realising the interest goes both ways. He wants affection and sex, companionship and adventure, with women who enjoy exploring that life with him.</p>
<h2>An evening in Mexico City</h2>
<p>On a rooftop surrounded by art and conversation, two women invite him into their company. One is pregnant. Someone’s story sets all three laughing; a question about his music keeps them talking. The attraction grows within an evening that already has plenty happening.</p>
<p>A first encounter begins with the woman or women approaching him. Tiggy answers with his own humour, interest and desire. Each has something to bring to the meeting, and each enjoys finding out what the others have in mind.</p>
<h2>Desire in many forms</h2>
<p>His attraction reaches across different bodies, backgrounds and personalities. A woman’s cheekiness, energy or delight in an idea is as much a part of the encounter as the way she looks at him. Quiet warmth and exuberant flirtation give him different pleasures.</p>
<p>His desires include conceiving a child with a consenting woman who shares that wish, and appreciating the beauty of pregnancy. He hopes to meet single women who are interested in him, start the conversation and invite him into an honest, uncomplicated connection.</p>
<p>He respects existing relationships and vows, with no wish to draw anyone away from a partner or husband. Affection, sex and adventure follow mutual interest, with intentions openly expressed. Conception belongs to a particular shared wish, rather than a goal for every encounter.</p>
<h2>Love across a travelling life</h2>
<p>He enjoys the freshness of a new meeting and the familiarity of someone he already loves. A journey brings departures as well as arrivals. He wants relationships that stay alive through messages, shared projects and occasions to be together again, alongside the freedom to keep exploring.</p>
<p>Luke’s travels in Thailand included both a journey with a girlfriend and later visits alone. His memories of forthright invitations, friendship and attraction give Tiggy’s travel romances a lived starting point. The fiction follows its own encounters from there.</p>
<h2>Several people, larger possibilities</h2>
<p><a href="https://auraofintelligence.github.io/australiansire/group-marriages.html">Global Group Marriages</a> extends the horizon towards relationships involving several partners across countries, with affection, shared pleasure, parenting and practical life entwined. The United Nations of Love imagines the UN as one loving, sexually alive, cross-cultural marriage raising children together. GAJRA Earth places that thought experiment within a wider planetary life.</p>
<p>For Tiggy, those possibilities grow from the desire to love and be loved in abundance. Some stories follow a brief meeting; others follow a reunion, a circle of lovers or a shared future. He remains curious about the people involved and the life they want to enjoy together.</p>'''),
    dict(slug='out-about', title='World travel', intro='Every country and territory, with work, romance and big experiences along the way.', image='out-about-world', alt='Two adult Thai women invite Tiggy to an evening gathering beside a Bangkok canal and an arriving passenger boat.', caption='Imagined canal-side encounter in Bangkok. GenAI artwork.', colour='lemon', body='''
<p class="lead">Tiggy’s ambition is every country and territory. He wants to meet, share, learn and teach, with enough happening along the way to make the journey worth remembering. There is work involved, time is short and a good invitation is worth paying attention to.</p>
<h2>Bangkok, before the boat arrives</h2>
<p>Beside a canal, two women start talking to him while a passenger boat approaches. Their conversation runs from the gathering they are heading to, to the creative work that brought him into town. The engine grows louder. They are still laughing when it is time to board.</p>
<p>A city has its own pace, sounds and everyday pleasures. Tiggy enjoys being amongst them with people who have their own reasons for being there. Romance, work and sightseeing cross paths during an ordinary journey through the city.</p>
<h2>The working traveller</h2>
<p>Luke’s UK working holiday took him through bar work, office demolition at Tower 42 and a gift-card factory before the festival season. Darwin later brought airport check-in, boarding and airside work on the Cairns-Darwin-Singapore route. Bowen Basin shutdowns brought another working landscape entirely.</p>
<p>Those memories give Tiggy experience of travel from several directions: arriving for a job, helping other people depart, building a temporary event and finishing work within a tight window. His <a href="art.html">practical skills</a> travel alongside his appetite for company and fun.</p>
<h2>Different places, different pleasures</h2>
<p>India, Nepal, Thailand and Abu Dhabi belong to Luke’s travel history. Tiggy’s wish list reaches further: outback gatherings and beach cultures, sport, city nightlife, high society and festivals across continents. He enjoys the variety, from a casual game with new friends to an evening where everybody has dressed splendidly.</p>
<p>A short working visit still holds encounters worth following. <a href="https://auraofintelligence.github.io/global-founder-atlas/">Global Founder Atlas</a> connects the wider work with research, residencies and projects. <a href="https://auraofintelligence.github.io/right-place-right-time/">Right Place, Right Time</a> follows the relationship between useful work and the next opportunity.</p>
<h2>The oracle follows the opportunity</h2>
<p>His travel oracle brings together invitations, work, events, resources, seasons and the interests he feels like pursuing. A festival date, a promising swell or a message from someone he wants to see gives the next decision its shape.</p>
<p>The ambition spans the globe; the route develops through life. He wants time for the experiences that matter, including a return journey when the company is worth it. Music, romance and <a href="water.html">a coast with good waves</a> each give him a different reason to go.</p>'''),
    dict(slug='water', title='Bodyboarding', intro='An epic wave, a fast ride and two women sharing the fun in the surf.', image='water-photo-carry-v6', alt='Long-haired Tiggy walks through shallow surf with two smiling adult women. Each carries a bodyboard under an arm and a pair of short swim flippers in the same hand. A blue-green wave peels behind them.', caption='After the ride. GenAI story concept.', colour='mint', body='''
<p class="lead">A clean face opens ahead of him. Tiggy’s board picks up speed, spray flies past and the whole ride fills his attention. Two women are out enjoying the same swell. Afterwards, wet-haired and laughing, they come through the shallows with boards under their arms and flippers in hand.</p>
<h2>That burst of speed</h2>
<p>Riding an epic wave is one of his ambitions. He loves the rush along the face, the rising lip and the moment the ride carries him further than he expected. The next set approaches while he is still feeling the last one.</p>
<p>His pleasure in bodyboarding runs through his travelling life. A good coast gives him a reason to unpack the board. A promising swell gives the oracle another opportunity to bring into the journey.</p>
<h2>Company in the water</h2>
<p>A woman starts the conversation at the beach. Her friend joins them, flippers in hand, and they talk about the waves they have just watched coming through. Tiggy is interested in both the swell and the company.</p>
<p>Out in the water, each is absorbed in her own ride. The laughter afterwards belongs to the shared day: sun, salt, wet hair, flushed faces and the exhilaration of coming in together. Flirtation grows alongside the fun of being there.</p>
<h2>The Sunshine Coast years</h2>
<p>Luke remembers bodyboarding so often that it competed successfully with his first term at the University of the Sunshine Coast. He left classes for the waves and eventually left the course. There were supermarket shifts at Buderim, months living in Maroochydore and Mooloolaba, parties, relationships and an early reputation as an easygoing beach bum.</p>
<p>Those memories give Tiggy’s surf stories a younger life to return to. Work finished, the board was ready and the coast offered somewhere to go. His adventures carry that appetite into new places and new company.</p>
<h2>A swell worth remembering</h2>
<p>Luke recalls waiting for cyclone swells around Minjerribah and riding some of his largest waves at Dickies Reef off the Moffat headland. He remembers a 42-inch Mike Stewart signature board, a bicep leash and the intense adrenaline of those rides.</p>
<p>Tiggy’s epic-wave ambition grows from that feeling. The fiction follows the anticipation, the ride and the people sharing the day with him. Other coasts lie ahead in his <a href="out-about.html">world travels</a>; the thrill of a good wave is already familiar.</p>'''),
    dict(slug='art', title='Art, memory and Aura', intro='A photograph, a remembered place and an idea taking shape between people.', image='memory-atlas-v2', alt='Tiggy and two adult artists explore a place-and-memory timeline beside a globe and human digital twin in a bright harbour studio.', caption='Imagined memory and digital-twin studio. GenAI artwork.', colour='blue', body='''
<p class="lead">Tiggy’s art begins with things that catch his attention: a place, a memory, an unfamiliar instrument, a shape he wants to build. Web, design, mechanical, electrical and event skills give him several ways to follow the idea.</p>
<h2>A studio full of places</h2>
<p>In a harbour studio, two artists bring him into a conversation about a globe, a human digital twin and a timeline of remembered journeys. Tiggy has stories to add. A point on the map leads to a job, a photograph leads to a person, and the afternoon grows around what each remembers.</p>
<p>Art, science and philosophy mingle in the making. The group tries out an image, rearranges the display and follows an idea none of them arrived with. Shared curiosity gives the work its energy.</p>
<h2>The hands behind the imagination</h2>
<p>Luke’s Caboolture automotive traineeship included servicing, brakes, steering, suspension and wheel alignment. Festival work later added the experience of helping an event take physical shape. Community web design and practical jobs carried that making into other settings.</p>
<p>Tiggy enjoys both the imagined object and the work of bringing it into view. A light sculpture, a digital space or an event installation offers something to share with people whose skills differ from his. Building Aura O.Z. with a team is one of his largest ambitions.</p>
<h2 id="remembering">Body, mind and place/soul story</h2>
<p>Luke maps his digital twins through body, mind and place/soul story: the physical person, the thinking person and a life remembered through places. His <a href="https://auraofintelligence.github.io/Lukes-world-of-work-experience/">work history map</a> already traces jobs, education and volunteering. A travel history map is planned.</p>
<p>His experience with 360-degree photography and VR adds another way to remember being somewhere. A room, a route or a view becomes more than a dot on a map. Tiggy’s flashbacks move through those remembered spaces, with people and experiences attached.</p>
<h2>The photograph that disappeared</h2>
<p>At Glastonbury in 2004, Luke remembers a sunshower and a rainbow reaching the Pyramid Stage while he sat near the stone circle. He photographed it on a Sony Cyber-shot. The memory card later became corrupted and the image was lost.</p>
<p>The memory survived the photograph. It is a vivid thread between the festival worker and the <a href="music.html">performance dream</a>. In Tiggy’s fiction, remembered places meet new art, music and experiences.</p>
<h2>Worlds on the workbench</h2>
<p>Aura’s <a href="https://auraofintelligence.github.io/world-builder.html">World Builder</a> extends the scale through landscapes, planets, moons, stars and galaxies. A lifetime’s places sit beside worlds still being imagined. Tiggy’s interest is in getting amongst them: making, remembering and discovering with other people.</p>'''),
    dict(slug='music', title='Music and Glastonbury', intro='From a Glastonbury crew pass to i C. infinity on stage. A long-held dream finds a new instrument.', image='music-sway-v2', alt='Tiggy experiments with an Audima Sway-inspired MIDI controller while two adult women, one visibly pregnant, enjoy the music in an imagined rehearsal space.', caption='Imagined Sway rehearsal. GenAI artwork.', colour='blue', body='''
<p class="lead">Tiggy wants to perform i C. infinity for a living audience: to hear the music fill a space, feel a crowd respond and enjoy the moment with the people around him. The music is Luke’s. The performance dream began in a festival field in 2004.</p>
<h2 id="glastonbury">The crew pass</h2>
<p>Luke’s UK working holiday included a season with W.A.A.P. Wing and a Prayer Event Services, setting up major festivals including Glastonbury. He arrived as part of the crew. Somewhere in that experience grew the wish to return someday as a performer.</p>
<p>The <a href="https://auraofintelligence.github.io/Lukes-world-of-work-experience/">work history map</a> records that season. Tiggy’s stories follow the connection between the work that makes a festival happen and the pleasure of being there when it comes alive. The old lanyard belongs to one chapter; a future set belongs to another.</p>
<h2 id="sway">Sway is on its way</h2>
<p>Luke has bought an <a href="https://audima.com.au/op/sway-b4/">Audima Labs Sway MIDI controller</a> from batch 4, with arrival expected in November or December 2026. Once it arrives, his goal is to learn to perform i C. infinity with it.</p>
<p>Tiggy’s imagined rehearsal starts small: his hands on an unfamiliar controller, music changing as he experiments, friends listening and laughing with him between attempts. One woman is pregnant; both enjoy the evening’s discoveries. A sound worth keeping brings them back to the music.</p>
<h2>The festival that never happened</h2>
<p>Luke planned an Earth Arts and Music Festival at Naukuchiatal in India’s Himalayan foothills. It was never held. Story Forge gives that unrealised project another life in fiction, with art, technology, ecology and music gathered beside the lake.</p>
<p>Tiggy’s story arrives at a festival already busy with artists, musicians and people enjoying themselves. An invitation draws him into a conversation beside a musical light sculpture. Stage sound travels across the water while a different sort of performance dream begins to feel close.</p>
<h2>Music, place and company</h2>
<p><a href="https://auraofintelligence.github.io/i-C-infinity-music-universe/">i C. infinity</a> holds several visual and musical worlds. Coastal light, ferry windows and campfire circles belong to Songs of Straddie; ancient ruins, signal towers and waking machine intelligence belong to Chronicles of the Forgotten.</p>
<p>Those different worlds give Tiggy’s performances their own settings. An island gathering and a <a href="possibilities.html">festival beyond Earth</a> bring very different crowds. The desire to share the music remains personal. Glastonbury is still the dream venue, with a great many possible beginnings on the way there.</p>'''),
    dict(slug='retreats', title='Aura retreats', intro='Aura, creative technology and a few days together, with plenty happening beyond the workshop.', image='retreat', alt='A visibly pregnant adult woman shares a playful light sculpture with Tiggy and another participant at an imagined coastal Aura retreat in Goa.', caption='Imagined Aura retreat in Goa. GenAI artwork.', colour='mint', body='''
<p class="lead">In Goa, a light sculpture changes as people move around it. Tiggy and a pregnant woman are laughing over the shape they have just made. Someone joins them with another idea. The conversation keeps going after they step away from the table.</p>
<h2>Making an Aura</h2>
<p>Luke’s retreat concept brings AI and extended reality into an exploration of the Aura of Intelligence. Avatars, body mapping and digital twins give participants ways to work with their own image, memories and intentions.</p>
<p>Tiggy enjoys the mix of hands-on making and unfamiliar ideas. A body model becomes an avatar. A remembered place becomes a digital room. Different people arrive with different pictures of themselves, and the creative work gives them something interesting to share.</p>
<h2>Five days, or nine</h2>
<p>The proposed formats are a five-day exploration and a nine-day teacher-training retreat. The longer format develops the practice of sharing Aura concepts with others. Generative AI, 3D modelling and printing, smart objects and memory palaces belong to the wider programme.</p>
<p>For Tiggy, the attraction includes the people making it happen: artists, coders, researchers and other curious participants. He brings practical skills and his own ideas. The pleasure of learning runs through the experience of doing things together.</p>
<h2>The life around the making</h2>
<p>Goa is among the proposed locations. Food, music, movement, dance, language and local excursions extend the experience beyond the workshop. A shared meal gives a conversation time to wander. An evening gathering brings different company around the table.</p>
<p>Friendship and attraction grow within that wider life. A woman begins a flirtation; Tiggy enjoys answering it. They have creative work to talk about, a place to explore and their own reasons for wanting more time together.</p>
<h2>When the stay ends</h2>
<p>The Forge’s retreat-pod story follows a group who become close during a short stay, then face the question of what happens afterwards. It is another possible relationship story, alongside the five- and nine-day Aura formats.</p>
<p>Tiggy’s travelling life carries that question with it. A few days of company become memories, ongoing conversations or a reason to meet again somewhere else. He enjoys the intensity of a shared experience and remains interested in what follows.</p>
<p><a href="art.html#remembering">Art and memory</a> keep a record of the place. <a href="out-about.html">The travel oracle</a> brings the next opportunities into view. The people give him something more personal to look forward to.</p>'''),
    dict(slug='possibilities', title='Beyond Earth', intro='A festival of whole civilisations, lunar play and an audience somewhere beyond Earth.', image='worldbuilding-festival-v2', alt='Tiggy and two adult worldbuilders, one visibly pregnant, share a civilisation model at an imagined future festival, with lunar and city simulations behind them.', caption='Imagined Worldbuilding Challenge Festival. GenAI artwork.', colour='lemon', body='''
<p class="lead">Tiggy’s next great experience reaches beyond the next country. His science-fiction romantasy follows humanity across planets, towards the energy ambitions of the Kardashev scale and into encounters with extraterrestrial and extra-dimensional civilisations. Art, pleasure, work and relationships travel into that future with him.</p>
<h2>The Worldbuilding Challenge Festival</h2>
<p>At the Forge’s imagined futures festival, teams pitch whole civilisations. A week moves from the Pitch Arena into a Build Sprint, ending with a 12-minute film, a working simulation and a world bible. An island campus residency is among the possibilities that follow.</p>
<p>Tiggy’s interests meet in the bustle: filmmakers, artists, scientists and people with very different ideas about a good life. He is drawn to the workbench, the projected world and the conversation that continues when a presentation finishes. A civilisation model gives a group something enormous to make together.</p>
<h2>Play on the Moon</h2>
<p><a href="https://auraofintelligence.github.io/space-industry.html">Moonlight Frontier</a> imagines lunar adventure and low-gravity sport. Tiggy’s bodyboarding appetite finds a different physical playground: unfamiliar movement, a longer leap and the amusement of discovering how his body feels there.</p>
<p>On Earth he remembers a ride through salt water. Here the view reaches across a lunar landscape. Companions share the surprise and the laughter, each enjoying the experience in her own way. His love of play follows him into a very different place.</p>
<h2>A solar system worth exploring</h2>
<p>The Forge’s Virtual Solar Swarm imagines one observing instrument distributed across the solar system. Its Helios Solar Observatory looks towards the Sun from several directions. These are research concepts feeding a much larger fictional horizon.</p>
<p>For Tiggy, that scale becomes a world to enter with people: a visit, a creative collaboration, music and conversation beneath an extraordinary view. Luke’s volunteer AI strategy work with Space Development Nexus in India gives the spaceward imagination a thread back to his own travels.</p>
<h2>A crowd beyond Earth</h2>
<p>He dreams of performing at Glastonbury. The fiction asks where the music travels after that. An orbital gathering has its own audience, acoustics and view. A civilisation with unfamiliar senses hears something in i C. infinity that he never expected.</p>
<p>An artist begins a conversation after the performance. They talk about what each experienced, and the encounter grows through that mutual curiosity. Contact opens into art, friendship and romance, with other intelligences bringing their own ideas into the meeting.</p>
<h2>The horizon being built</h2>
<p>Luke sees today’s spaceflight, AI and robotics work as early ingredients of a much larger future. <a href="https://www.nasa.gov/moontomarsarchitecture-strategyandobjectives/">NASA’s Moon to Mars strategy</a> and <a href="https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/">Gemini Robotics</a> connect that curiosity to present work. Interstellar encounters and travel across dimensions belong to the speculative stories.</p>
<p><a href="https://auraofintelligence.github.io/gajra-earth-claude-build/ahead.html">GAJRA Earth</a> carries joyful responsible abundance into the planetary imagination. Tiggy is interested in the life within that scale: the music, food, company, useful work and enjoyment of being there. The universe grows vast. The encounters remain personal.</p>'''),
    dict(slug='sitemap', title='Site map', intro='Travel, desire, waves, memory, music and worlds beyond Earth. Follow the thread that catches your interest.', image='wayfinder', alt='Brightly coloured sculptural archways lead along a sunny seaside festival walkway towards the ocean.', caption='An imagined seaside festival walkway. GenAI artwork.', colour='orange', body='''
<p class="lead">Tiggy’s adventures grow from Luke’s memories and the worlds taking shape around Aura. The chapters above follow his character; these links reach into the life and creative ecosystem behind him.</p>
<h2>The creator and the stories</h2>
<p><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/">Man and Mind</a> introduces Luke Nathan Hayes. <a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Story Forge</a> gathers characters, settings and developing stories. <a href="https://auraofintelligence.github.io/loose-goose-comedy-engine/">Loose Goose Comedy Engine</a> follows the humour.</p>
<h2>The lived past and the next journey</h2>
<p>The <a href="https://auraofintelligence.github.io/Lukes-world-of-work-experience/">work history map</a> traces jobs, education and volunteering. <a href="https://auraofintelligence.github.io/right-place-right-time/">Right Place, Right Time</a> follows working opportunities. <a href="https://auraofintelligence.github.io/i-C-infinity-music-universe/">i C. infinity</a> opens the music catalogue and its visual worlds.</p>
<h2>Beach life and the wider horizon</h2>
<p>The proposed <a href="https://auraofintelligence.github.io/ballow-road-sand-screen-hub/">Ballow Road Sand &amp; Screen Hub</a> brings sand sports, outdoor cinema, markets and festivals into Luke’s beach-hub idea for Minjerribah. The <a href="https://auraofintelligence.github.io/sitemap.html">Aura site map</a> and <a href="https://auraofintelligence.github.io/project-atlas/site-map.html">Project Atlas</a> lead through the wider collection of projects and imagined futures.</p>'''),
]

FESTIVAL = '''<section class="chapter-feature" aria-labelledby="festival-title"><div class="feature-copy"><h2 id="festival-title">Naukuchiatal, another beginning</h2><p>Luke’s Earth Arts and Music Festival was planned and never held. In Tiggy’s fiction, lights gather beside the Himalayan lake, stage sound carries across the water and a conversation begins around a musical sculpture.</p><p>A remembered crew pass and an unrealised festival meet a future performance dream. <a href="music.html">Follow the music and Glastonbury story ↗</a></p></div><figure class="hero"><img src="assets/naukuchiatal-festival.webp" alt="Long-haired Tiggy and two adult Indian women, one visibly pregnant, laugh around an illuminated musical sculpture at an imagined lakeside arts festival in Naukuchiatal, with green hills, a stage and a lively crowd behind them." width="1536" height="1024" loading="lazy"><figcaption>Earth Arts and Music Festival imagined at Naukuchiatal. GenAI artwork.</figcaption></figure></section>'''

PLAY = '''<section class="play-panel" aria-labelledby="play-title"><div><h2 id="play-title">Follow an interest</h2><p>Music, bodyboarding and world travel.</p><div class="mood-buttons" role="group" aria-label="Choose an interest"><button type="button" data-mood="make" aria-pressed="true">Music</button><button type="button" data-mood="wander" aria-pressed="false">Waves</button><button type="button" data-mood="company" aria-pressed="false">Travel</button></div><div class="play-result" aria-live="polite" aria-atomic="true"><h3>Music and Glastonbury</h3><p>A Glastonbury crew pass, i C. infinity and a Sway controller on its way. Tiggy wants to take the music on stage.</p></div></div><a class="round-link" href="music.html" aria-label="Music and Glastonbury">↗</a></section>'''

def chapter_links():
    return '<nav class="chapter-index" aria-label="Tiggy’s chapters"><h2>Chapters</h2>'+''.join(f'<a href="{p["slug"]}.html"><span class="chapter-copy"><strong>{escape(p["title"])}</strong><span>{escape(p["intro"])}</span></span><span aria-hidden="true">↗</span></a>' for p in PAGES[:-1])+'</nav>'

for i,p in enumerate(PAGES):
    prev=PAGES[(i-1)%len(PAGES)];nxt=PAGES[(i+1)%len(PAGES)]
    nav=''.join(f'<a href="{q["slug"]}.html"'+(' aria-current="page"' if q==p else '')+f'>{escape(q["title"])}</a>' for q in PAGES)
    extra=FESTIVAL+PLAY if i==0 else ''
    chapter_index=chapter_links() if p['slug']=='sitemap' else ''
    (ROOT/(p['slug']+'.html')).write_text(f'''<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(p['intro'],quote=True)}"><meta name="theme-color" content="#f7ff67"><title>{escape(p['title'])}{' | Tiggy Bestmann' if i else ' | Artist, fool and student of life'}</title><link rel="icon" href="assets/favicon.ico"><link rel="apple-touch-icon" href="assets/icon-180.png"><link rel="stylesheet" href="assets/site.css?v={VERSION}"><script defer src="assets/site.js?v={VERSION}"></script></head>
<body id="top" class="theme-{p['colour']} {'home' if i==0 else ''}"><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="index.html">Tiggy Bestmann<span class="brand-dot" aria-hidden="true"></span></a><div class="header-actions"><a class="partner-short" href="{escape(SIRE_URL,quote=True)}">Meet Sire ↗</a><button class="menu-button" type="button" aria-expanded="false" aria-controls="chapter-menu">Explore <span aria-hidden="true">+</span></button></div><nav id="chapter-menu" aria-label="Chapters" hidden>{nav}</nav></header>
<main id="main"><section class="opening"><h1>{escape(p['title'])}</h1><p>{escape(p['intro'])}</p></section><figure class="hero"><img src="assets/{p['image']}.webp" alt="{escape(p['alt'],quote=True)}" width="1536" height="1024" fetchpriority="high"><figcaption>{escape(p['caption'])}</figcaption></figure>{chapter_index}
<article class="prose" aria-label="{escape(p['title'],quote=True)}">{p['body']}</article>{extra}
</main>
<nav class="page-turn" aria-label="Previous and next pages"><a rel="prev" href="{prev['slug']}.html"><span>← Previous</span><strong>{escape(prev['title'])}</strong></a><a rel="next" href="{nxt['slug']}.html"><span>Next →</span><strong>{escape(nxt['title'])}</strong></a></nav>
<footer><p>Tiggy Bestmann<br>A fictional character by Luke Nathan Hayes.</p><nav class="footer-links" aria-label="Related sites and licence"><a href="sitemap.html">Site map ↗</a><a href="{escape(SIRE_URL,quote=True)}">Australian Sire</a><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Story Forge</a><a href="https://auraofintelligence.github.io/loose-goose-comedy-engine/">Loose Goose Comedy Engine</a><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/">Man and Mind</a><a href="https://github.com/auraofintelligence/tiggy-bestmann/blob/main/LICENCE.md">Strange But True licence</a></nav></footer><a class="to-top" href="#top" aria-label="Back to top">↑</a></body></html>''',encoding='utf-8')
print(f'Built {len(PAGES)} Tiggy pages.')
